### ISSUE TITLE
Missing license/attribution for java_external_lib JARs

### ISSUE THREAD

**Issue by stain** [klugem/watchdog#4]
Several of the files in java_external_lib have licenses that require them to be provided to the user, but they are missing or not easy to find in watchdog.

For instance `commons-codec-1.10.jar` is licensed under https://www.apache.org/licenses/LICENSE-2.0 and can be used and redistributed by GPL 3, but only according to clause 4 in the license:

4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions (my emphasis):

>    **4. Redistribution** You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
> a) You must give any other recipients of the Work or Derivative Works a **copy of this License**; and
>   b) You must cause any modified files to carry prominent notices stating that You changed the files; and
>  c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
>   d) If the Work includes a "NOTICE" text file as part of its distribution, then **any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file**, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: **within a NOTICE text file distributed as part of the Derivative Works**; **within the Source form or documentation**, if provided along with the Derivative Works; or, within a **display generated** by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.
>     You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

I do find that LICENSE.txt and NOTICE.txt is contained inside some of the JAR files, e.g.:

```
(base) stain@biggie:~/src/watchdog/java_external_lib$ cat ./commons-io-2.4/META-INF/NOTICE.txt
Apache Commons IO
Copyright 2002-2012 The Apache Software Foundation

This product includes software developed by
The Apache Software Foundation (http://www.apache.org/).
```

..but not all of them. These are missing any kind of license at all: nanoHTTPD, jsch-0.1.54, jcommander-1.30, SGE_61_drmaa (and others?)

As some of these are a bit more obscure dependencies I don't know where they come from or their license.

Some only contain license hidden as part of their META-INF/maven pom files: slf4j-api-1.7.21 gson-2.8.5 etc.

The clause d) on NOTICE means you have to lift these to the root project, either add your own NOTICE, add their content to the documentation. The good news if the upstream JARs don't have any NOTICE.txt you probably just have to propagate their license text or leave it in place where it is.

It is probably still good to also lift their LICENSE.txt etc to licenses/  (which you may download) so users and devs know what is the license of the whole of watchdog, specially considering GPL 3 means you have committed to providing the source code for each of the JARs you are redistributing.

**Comment by klugem** [comment]
Licenses are now obtained as described in #3 by the Maven build script.
